# Generated by Django 5.2.6 on 2025-09-23 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0002_remove_quiz_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_options',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
